apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pk-portal-ingress
  namespace: pk-portal
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: pk-portal.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pk-portal-app
                port:
                  number: 80
