apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pk-portal-ingress
  namespace: pk-portal
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pk-portal.peak-processing.com`)
      kind: Rule
      services:
        - name: pk-portal-app
          port: 80
